#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/chiron

PRODUCT_COPY_FILES += \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Bluetooth_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_General_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Global_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Handset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Hdmi_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Headset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Speaker_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_workspaceFile.qwsp \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/chiron_imx386_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_imx386_semco_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/chiron_ov5675_primax_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_ov5675_primax_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/chiron_ov5675_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_ov5675_qtech_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/dualcamera.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dualcamera.png \
    vendor/xiaomi/chiron/proprietary/vendor/etc/elliptic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/qdcm_calib_data_jdi_fhd_video_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_jdi_fhd_video_dsi_panel.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/chiron/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/chiron/proprietary/vendor/etc/thermal-engine-8998-high.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-8998-high.conf \
    vendor/xiaomi/chiron/proprietary/vendor/etc/thermal-engine-8998.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-8998.conf \
    vendor/xiaomi/chiron/proprietary/vendor/firmware/tas2559_s_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2559_s_uCDSP.bin \
    vendor/xiaomi/chiron/proprietary/vendor/firmware/tas2559_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2559_uCDSP.bin

PRODUCT_PACKAGES += \
    libactuator_chiron_imx386_ak7372_semco \
    libchromatix_chiron_imx386_semco_4K_preview \
    libchromatix_chiron_imx386_semco_4K_video \
    libchromatix_chiron_imx386_semco_common \
    libchromatix_chiron_imx386_semco_cpp_hfr_120 \
    libchromatix_chiron_imx386_semco_cpp_hfr_60 \
    libchromatix_chiron_imx386_semco_cpp_hfr_90 \
    libchromatix_chiron_imx386_semco_cpp_liveshot \
    libchromatix_chiron_imx386_semco_cpp_preview \
    libchromatix_chiron_imx386_semco_cpp_snapshot \
    libchromatix_chiron_imx386_semco_cpp_snapshot_hdr \
    libchromatix_chiron_imx386_semco_cpp_snapshot_hht \
    libchromatix_chiron_imx386_semco_cpp_video \
    libchromatix_chiron_imx386_semco_cpp_video_hdr \
    libchromatix_chiron_imx386_semco_default_preview \
    libchromatix_chiron_imx386_semco_default_video \
    libchromatix_chiron_imx386_semco_hdr_snapshot_3a \
    libchromatix_chiron_imx386_semco_hdr_video_3a \
    libchromatix_chiron_imx386_semco_hfr_120 \
    libchromatix_chiron_imx386_semco_hfr_120_3a \
    libchromatix_chiron_imx386_semco_hfr_60 \
    libchromatix_chiron_imx386_semco_hfr_60_3a \
    libchromatix_chiron_imx386_semco_hfr_90 \
    libchromatix_chiron_imx386_semco_hfr_90_3a \
    libchromatix_chiron_imx386_semco_liveshot \
    libchromatix_chiron_imx386_semco_postproc \
    libchromatix_chiron_imx386_semco_preview \
    libchromatix_chiron_imx386_semco_snapshot \
    libchromatix_chiron_imx386_semco_snapshot_hdr \
    libchromatix_chiron_imx386_semco_video \
    libchromatix_chiron_imx386_semco_video_hdr \
    libchromatix_chiron_imx386_semco_zsl_preview \
    libchromatix_chiron_imx386_semco_zsl_video \
    libchromatix_chiron_ov5675_primax_a3_default_preview \
    libchromatix_chiron_ov5675_primax_a3_default_video \
    libchromatix_chiron_ov5675_primax_a3_hfr_120 \
    libchromatix_chiron_ov5675_primax_a3_hfr_60 \
    libchromatix_chiron_ov5675_primax_a3_hfr_90 \
    libchromatix_chiron_ov5675_primax_common \
    libchromatix_chiron_ov5675_primax_cpp_ds_chromatix \
    libchromatix_chiron_ov5675_primax_cpp_hfr_120 \
    libchromatix_chiron_ov5675_primax_cpp_hfr_60 \
    libchromatix_chiron_ov5675_primax_cpp_hfr_90 \
    libchromatix_chiron_ov5675_primax_cpp_liveshot \
    libchromatix_chiron_ov5675_primax_cpp_preview \
    libchromatix_chiron_ov5675_primax_cpp_snapshot \
    libchromatix_chiron_ov5675_primax_cpp_us_chromatix \
    libchromatix_chiron_ov5675_primax_cpp_video \
    libchromatix_chiron_ov5675_primax_cpp_video_full \
    libchromatix_chiron_ov5675_primax_default_video \
    libchromatix_chiron_ov5675_primax_hfr_120 \
    libchromatix_chiron_ov5675_primax_hfr_60 \
    libchromatix_chiron_ov5675_primax_hfr_90 \
    libchromatix_chiron_ov5675_primax_liveshot \
    libchromatix_chiron_ov5675_primax_postproc \
    libchromatix_chiron_ov5675_primax_preview \
    libchromatix_chiron_ov5675_primax_snapshot \
    libchromatix_chiron_ov5675_primax_video_full \
    libchromatix_chiron_ov5675_primax_zsl_preview \
    libchromatix_chiron_ov5675_primax_zsl_video \
    libchromatix_chiron_ov5675_qtech_a3_default_preview \
    libchromatix_chiron_ov5675_qtech_a3_default_video \
    libchromatix_chiron_ov5675_qtech_a3_hfr_120 \
    libchromatix_chiron_ov5675_qtech_a3_hfr_60 \
    libchromatix_chiron_ov5675_qtech_a3_hfr_90 \
    libchromatix_chiron_ov5675_qtech_common \
    libchromatix_chiron_ov5675_qtech_cpp_ds_chromatix \
    libchromatix_chiron_ov5675_qtech_cpp_hfr_120 \
    libchromatix_chiron_ov5675_qtech_cpp_hfr_60 \
    libchromatix_chiron_ov5675_qtech_cpp_hfr_90 \
    libchromatix_chiron_ov5675_qtech_cpp_liveshot \
    libchromatix_chiron_ov5675_qtech_cpp_preview \
    libchromatix_chiron_ov5675_qtech_cpp_snapshot \
    libchromatix_chiron_ov5675_qtech_cpp_us_chromatix \
    libchromatix_chiron_ov5675_qtech_cpp_video \
    libchromatix_chiron_ov5675_qtech_cpp_video_full \
    libchromatix_chiron_ov5675_qtech_default_video \
    libchromatix_chiron_ov5675_qtech_hfr_120 \
    libchromatix_chiron_ov5675_qtech_hfr_60 \
    libchromatix_chiron_ov5675_qtech_hfr_90 \
    libchromatix_chiron_ov5675_qtech_liveshot \
    libchromatix_chiron_ov5675_qtech_postproc \
    libchromatix_chiron_ov5675_qtech_preview \
    libchromatix_chiron_ov5675_qtech_snapshot \
    libchromatix_chiron_ov5675_qtech_video_full \
    libchromatix_chiron_ov5675_qtech_zsl_preview \
    libchromatix_chiron_ov5675_qtech_zsl_video \
    libmmcamera_chiron_imx386_semco \
    libmmcamera_chiron_imx386_semco_eeprom \
    libmmcamera_chiron_ov5675_primax \
    libmmcamera_chiron_ov5675_primax_eeprom \
    libmmcamera_chiron_ov5675_qtech \
    libmmcamera_chiron_ov5675_qtech_eeprom \
    fingerprint.fpc.msm8998 \
    fingerprint.goodix.msm8998 \
    libgf_ca \
    libgf_hal \
    sensors.elliptic
